#!/usr/bin/env bash
# Stage the 4 Unity templates living at E:\UnityTemplate into a clean
# checkout-able git tree. Strips Library/Logs/Temp/UserSettings/obj/
# Builds/ (Unity-regenerated cruft) and ships only Assets / Packages /
# ProjectSettings — the minimum required to open the project in Unity.
#
# Run once before the first git push:
#     bash backend/scripts/stage_templates.sh
#
# Result: /tmp/mycrew-templates-stage/{Universal2D,Universal3D,ARMobile,MRCore}
set -euo pipefail

SRC="/e/UnityTemplate"
DST="${1:-/tmp/mycrew-templates-stage}"

# Mapping: original folder name → git-friendly subdir (no spaces, no
# special chars). Must match TEMPLATE_ID_TO_DIR in
# backend/services/template_cloner_svc.py so backend can sparse-checkout
# the right subdir.
declare -A MAP=(
  ["Universal 2D"]="Universal2D"
  ["Universal 3D"]="Universal3D"
  ["AR Mobile"]="ARMobile"
  ["MR Core"]="MRCore"
)

# Things to drop. Unity regenerates everything below from Assets/ +
# Packages/manifest.json on next editor open.
EXCLUDES=(
  "--exclude=Library/"
  "--exclude=Logs/"
  "--exclude=Temp/"
  "--exclude=obj/"
  "--exclude=Builds/"
  "--exclude=Build/"
  "--exclude=UserSettings/"
  "--exclude=*.csproj"
  "--exclude=*.sln"
  "--exclude=.vs/"
  "--exclude=.vscode/"
  "--exclude=.idea/"
  "--exclude=.DS_Store"
  "--exclude=Thumbs.db"
)

mkdir -p "$DST"
echo "Staging into: $DST"

for src_name in "${!MAP[@]}"; do
  dst_name="${MAP[$src_name]}"
  echo "  → $src_name → $dst_name"
  mkdir -p "$DST/$dst_name"
  rsync -a "${EXCLUDES[@]}" "$SRC/$src_name/" "$DST/$dst_name/"
done

# Top-level .gitignore safety net — even if a future stage missed an
# exclude, git won't pick it up.
cat > "$DST/.gitignore" <<'GITIGNORE'
# Unity-regenerated — never commit
**/Library/
**/Logs/
**/Temp/
**/obj/
**/Builds/
**/Build/
**/UserSettings/
**/.vs/
**/.vscode/
**/.idea/

# Generated by Unity on editor open
**/*.csproj
**/*.sln
**/*.unityproj
**/*.suo
**/*.tmp
**/*.user
**/*.userprefs
**/*.pidb
**/*.booproj
**/*.svd
**/*.pdb
**/*.opendb
**/*.VC.db
**/*.apk
**/*.aab
**/*.ipa

# OS junk
**/.DS_Store
**/Thumbs.db
GITIGNORE

# README so the GitHub repo isn't blank-looking
cat > "$DST/README.md" <<'README'
# MyCrew Unity Templates

Per-template checkouts used by MyCrew's project scaffolding flow.
Cloned by `backend/services/template_cloner_svc.py` when a user kicks
off a new project; the chosen subfolder is copied into the user's
chosen root directory and renamed to the project's English name.

## Layout

| Subdir          | Maps to template_id     |
|-----------------|-------------------------|
| `Universal2D/`  | `unity_universal_2d`    |
| `Universal3D/`  | `unity_universal_3d`    |
| `ARMobile/`     | `unity_ar_mobile`       |
| `MRCore/`       | `unity_mr_core`         |

Each subdir contains a stripped Unity project: `Assets/`, `Packages/`,
`ProjectSettings/`. Unity regenerates `Library/`, `Logs/`, `Temp/`,
`obj/`, the `.csproj`/`.sln` files, and `UserSettings/` on first
editor open, so none of those are committed here.

Do NOT add `Library/` etc back — they balloon the repo by 500MB+ each
without any value, and Unity will throw them away anyway.
README

# Per-template README pointer (helps when browsing on GitHub)
for src_name in "${!MAP[@]}"; do
  dst_name="${MAP[$src_name]}"
  cat > "$DST/$dst_name/README.md" <<EOF
# $src_name (Unity template)

Stripped Unity project — Assets / Packages / ProjectSettings only.
Open in Unity Editor; it will regenerate Library/ + project files on
first import.
EOF
done

echo "Done. Resulting size:"
du -sh "$DST"
