"""Stage 4 Unity templates from E:\\UnityTemplate into a clean
git-checkout-able tree at /tmp/mycrew-templates-stage (or arg 1).

Pure Python (no rsync) so it works on Git Bash / Windows without extra
deps. Skips Unity-regenerated cruft (Library / Logs / Temp / obj /
Builds / UserSettings / .csproj / .sln).
"""
from __future__ import annotations

import shutil
import sys
from pathlib import Path

SRC_ROOT = Path(r"E:\UnityTemplate")

# Original folder name → git-friendly subdir (no spaces). Must match
# TEMPLATE_ID_TO_DIR in services/template_cloner_svc.py.
NAME_MAP = {
    "Universal 2D": "Universal2D",
    "Universal 3D": "Universal3D",
    "AR Mobile": "ARMobile",
    "MR Core": "MRCore",
}

# Dirs Unity regenerates — never commit.
SKIP_DIRS = {
    "Library", "Logs", "Temp", "obj",
    "Builds", "Build",
    "UserSettings",
    ".vs", ".vscode", ".idea",
}
# File-name patterns to skip (case-insensitive suffix match).
SKIP_SUFFIXES = (
    ".csproj", ".sln", ".unityproj", ".suo",
    ".tmp", ".user", ".userprefs", ".pidb", ".booproj",
    ".svd", ".pdb", ".opendb",
    ".apk", ".aab", ".ipa",
)
SKIP_FILES = {".DS_Store", "Thumbs.db"}


GITIGNORE = """# Unity-regenerated — never commit
**/Library/
**/Logs/
**/Temp/
**/obj/
**/Builds/
**/Build/
**/UserSettings/
**/.vs/
**/.vscode/
**/.idea/

# Generated by Unity on editor open
**/*.csproj
**/*.sln
**/*.unityproj
**/*.suo
**/*.tmp
**/*.user
**/*.userprefs
**/*.pidb
**/*.booproj
**/*.svd
**/*.pdb
**/*.opendb
**/*.apk
**/*.aab
**/*.ipa

# OS junk
**/.DS_Store
**/Thumbs.db
"""

TOP_README = """# MyCrew Unity Templates

Per-template checkouts used by MyCrew's project scaffolding flow.
Cloned by `backend/services/template_cloner_svc.py` when a user kicks
off a new project; the chosen subfolder is copied into the user's
chosen root directory and renamed to the project's English name.

## Layout

| Subdir          | Maps to template_id     |
|-----------------|-------------------------|
| `Universal2D/`  | `unity_universal_2d`    |
| `Universal3D/`  | `unity_universal_3d`    |
| `ARMobile/`     | `unity_ar_mobile`       |
| `MRCore/`       | `unity_mr_core`         |

Each subdir is a stripped Unity project: Assets/, Packages/,
ProjectSettings/. Unity regenerates Library/, Logs/, Temp/, obj/,
.csproj/.sln, and UserSettings/ on first editor open, so none of
those are committed here.
"""


def _should_skip(p: Path) -> bool:
    name = p.name
    if name in SKIP_FILES:
        return True
    low = name.lower()
    return any(low.endswith(suf) for suf in SKIP_SUFFIXES)


def _walk_copy(src: Path, dst: Path) -> int:
    """Recursive copy with directory + extension filters. Returns
    number of files copied (informational)."""
    if not src.exists():
        return 0
    dst.mkdir(parents=True, exist_ok=True)
    copied = 0
    for child in src.iterdir():
        if child.is_dir():
            if child.name in SKIP_DIRS:
                continue
            copied += _walk_copy(child, dst / child.name)
        else:
            if _should_skip(child):
                continue
            shutil.copy2(child, dst / child.name)
            copied += 1
    return copied


def main() -> None:
    dst_root = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("/tmp/mycrew-templates-stage")
    dst_root.mkdir(parents=True, exist_ok=True)
    print(f"Staging into: {dst_root}")

    total_files = 0
    for orig, slug in NAME_MAP.items():
        src = SRC_ROOT / orig
        if not src.exists():
            print(f"  [SKIP] {orig} not found at {src}")
            continue
        dst = dst_root / slug
        print(f"  → {orig} → {slug}")
        if dst.exists():
            shutil.rmtree(dst)
        n = _walk_copy(src, dst)
        total_files += n
        per_readme = dst / "README.md"
        per_readme.write_text(
            f"# {orig} (Unity template)\n\n"
            "Stripped Unity project — Assets / Packages / ProjectSettings only.\n"
            "Open in Unity Editor; it will regenerate Library/ + project files on\n"
            "first import.\n",
            encoding="utf-8",
        )
        print(f"     copied {n} files")

    (dst_root / ".gitignore").write_text(GITIGNORE, encoding="utf-8")
    (dst_root / "README.md").write_text(TOP_README, encoding="utf-8")

    print(f"\nDone. Total files: {total_files}")


if __name__ == "__main__":
    main()
