from __future__ import annotations

from typing import Any, Protocol


class MCPPort(Protocol):
    async def connect(self, server_id: str, config: dict) -> None: ...
    async def disconnect(self, server_id: str) -> None: ...
    async def call_tool(self, server_id: str, tool_name: str, arguments: dict[str, Any]) -> str: ...
    async def list_tools(self, server_id: str) -> list[dict]: ...
    async def get_status(self, server_id: str) -> str: ...
    async def get_all_statuses(self) -> dict[str, str]: ...
